version: '3.8'


services:
  app:
    profiles: [ "prod" ]
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./vault/rendered/app.env
    environment:
      - PYTHONUNBUFFERED=1
      - RATE_LIMIT_POST_PER_MIN_PER_IP=10
      - RATE_LIMIT_BURST=2
      - RATE_LIMIT_LOGIN_PER_10MIN_PER_IP=5
      - RATE_LIMIT_LOGIN_PER_10MIN_PER_ACCOUNT=5
      - RATE_LIMIT_LOGIN_BLOCK_SECONDS=900
      - REDIS_URL=redis://redis:6379/0
    # DATABASE_URL и SECRET_KEY приходят из Vault
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      vault-agent:
        condition: service_healthy
    networks:
      - default


  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./vault/rendered/db.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
    # POSTGRES_PASSWORD из Vault
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    depends_on:
      vault-agent:
        condition: service_healthy
    networks:
      - default
